[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Retail Analytics: Building Intelligent Systems That Help Retailers Make Better Business Decisions"
